name: 'ðŸž Bug report'
description: Report an issue with Blueprints.
title: "[ðŸž Bug]: Add bug description title here."
labels: [bug]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the
            [latest version](https://pypi.org/project/blue-prints/) of Blueprints.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Issue description
      description: >
        Provide any additional information you think might be relevant.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Reproducible example
      description: >
        Please follow [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) on how to
        provide a minimal, copy-pastable example. Include the (wrong) output if applicable.
      value: |
        ```python

        ```
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: >
        Describe or show a code example of the expected behavior.
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Installed versions
      description: >
        Which version of the package are you using?
      value: |
        ```
        
        ```
    validations:
      required: true
