# blueprints/codes/eurocode/en_1993_1_9_2005/__init__.pyi

from . import annex_a_determination_of_fatigue_load_parameters_and_verification_formats as annex_a_determination_of_fatigue_load_parameters_and_verification_formats

from .annex_a_determination_of_fatigue_load_parameters_and_verification_formats.formula_a_1 import FormADot1DamageDuringDesignLife as FormADot1DamageDuringDesignLife
from .annex_a_determination_of_fatigue_load_parameters_and_verification_formats.formula_a_2 import FormADot2CriteriaBasedOnDamageAccumulation as FormADot2CriteriaBasedOnDamageAccumulation
